### ISSUE TITLE
Parameter "translations" does not exist

### ISSUE THREAD

**Issue by kusmierz** [dreamcommerce/google-adwords-remarketing#1]
I'm trying to setup the application. I've put it on the server and entered in shoper admin "https://xxxx/appstore" as my application url address. Unfortunately, while application installing, I've got 403 error `Parameter "transactions" does not exists`. In fact there is no such a param in GET nor POST. The `place` param is missing too.

![screen shot 2015-09-11 at 16 06 52](https://cloud.githubusercontent.com/assets/404344/9816754/299c0c40-589f-11e5-9064-ae0b02fd5a2f.png)

What am I doing wrong?

PS
There is also misspelling in the message error (redundant "s" at the end)

**Comment by kusmierz** [comment]
We've found correct url `https://xxxx/billing`. Anyway, after installing, the app returns an error.

```
2015-09-11 19:24:20 [debug]: NEW REQUEST: POST https://devshop-xxxxx.shoparena.pl/webapi/rest/metafields/SYSTEM?
2015-09-11 19:24:20 [debug]: Headers: array (
'Authorization' => 'Bearer xyz’,
'Content-Type' => 'application/json',
)
2015-09-11 19:24:20 [debug]: Document body: array (
'namespace' => 'GOOGLE_ADWORDS',
'key' => 'CONVERSION_ID_BASKET_DONE',
'type' => 3,
)
2015-09-11 19:24:20 [debug]: Document body (JSON-ified): {"namespace":"GOOGLE_ADWORDS","key":"CONVERSION_ID_BASKET_DONE","type":3}
2015-09-11 19:24:20 [debug]: Response headers: array (
0 => 'HTTP/1.1 400 Bad Request',
'Code' => '400',
'Status' => 'Bad Request',
'Server' => 'nginx',
'Date' => 'Fri, 11 Sep 2015 17:24:21 GMT',
'Content-Type' => 'application/json',
'Connection' => 'close',
'X-Shop-Api-Calls' => '1',
'X-Shop-Api-Bandwidth' => '1',
'X-Shop-Api-Limit' => '10',
'Cache-Control' => 'no-store',
'X-XSS-Protection' => '1; mode=block',
'X-Powered-By' => 'DreamCommerce S.A.',
)
2015-09-11 19:24:20 [debug]: Response body: {"error":"invalid_request","error_description":"This metafield is already registered"}
```

**Comment by jedi-pl** [comment]
It is not possible to add two metafields with the same namespace and key. 
The one you are trying to add is already registered.

Did you installed this app from our store? In that case, you already have this metafield added to shops database.

If you want to create your own app using this as a base code, I think you should use different namespace for your metafield e.g "MyApp_Namespace1"
