### ISSUE TITLE
Ability to create own page in the shop

### ISSUE THREAD

**Issue by kusmierz** [dreamcommerce/google-adwords-remarketing#2]
Is it possible to create your own page in the shop? In example I'd like to create http://devshop-xxx.shoparena.pl/appname/some-slug accessible by all users.

Examples:
- plugin/app about page
- some static pages
- redirections for affiliation integration (which will set cookie, etc)
- multi step administration for admins
- some extra configuration for shop's users
- etc

**Comment by jedi-pl** [comment]
This question is not relevant to google-adwords-remarketing app. It should be addressed to DreamCommerce Appstore Team via technical support.

It is not possible to create your own "pages" in shop's domain. Each application's action is triggered via specific link in the shop and resulting html is embeded in iframe.
