### ISSUE TITLE
Smarty's {$smarty} reserved variable

### ISSUE THREAD

**Issue by kusmierz** [dreamcommerce/google-adwords-remarketing#3]
Is is possible to use [{$smarty} reserved variable](http://www.smarty.net/docsv2/en/language.variables.smarty.tpl) in snippets? In example I'd like to show content if and only if there is correct cookie set.

**Comment by jedi-pl** [comment]
This question is not relevant to google-adwords-remarketing app. It should be addressed to DreamCommerce Appstore Team via technical support.

It is not possible
